# https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
name: Setup Environment Action

runs:
  using: 'composite'
  steps:
    - name: Install bun
      uses: oven-sh/setup-bun@v1
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Install dependencies
      run: bun install --frozen-lockfile
      shell: bash
